# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbroadPassApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='user_realname',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='provider',
            name='user_realname',
            field=models.CharField(default='', max_length=10),
        ),
    ]
