# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 02:09
from __future__ import unicode_literals

from django.db import migrations

from django.core.management import call_command
def loadfixture(apps,schema_editor):
    call_command('loaddata','initial_data.json')
class Migration(migrations.Migration):

    dependencies = [
        ('AbroadPassApp', '0004_auto_20160309_1004'),
    ]

    operations = [
        migrations.RunPython(loadfixture),
    ]
