# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 02:08
from __future__ import unicode_literals

from django.db import migrations

from django.core.management import call_command
def loadfixture(apps,schema_editor):
    call_command('loaddata','initial_data_major.json')
class Migration(migrations.Migration):

    dependencies = [
        ('AbroadPassApp', '0006_major'),
    ]

    operations = [
        migrations.RunPython(loadfixture),
    ]
