# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 06:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AbroadPassApp', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sub_title', models.CharField(max_length=30)),
                ('img_url', models.URLField()),
                ('score', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sell_num', models.IntegerField(default=0)),
                ('detail', models.TextField()),
                ('range', models.IntegerField(default=0)),
                ('is_recommend', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=30)),
                ('sub_category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sub_title', models.CharField(max_length=30)),
                ('img_url', models.URLField()),
                ('score', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('qq', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('detail', models.TextField()),
                ('range', models.IntegerField(default=0)),
                ('is_recommend', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=30)),
                ('sub_category', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 1, 6, 0, 17, 542000, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='course',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AbroadPassApp.Trainee'),
        ),
    ]
