# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 03:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AbroadPassApp', '0009_auto_20160401_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onlineapply_status', models.IntegerField(default=0)),
                ('cvapply_status', models.IntegerField(default=0)),
                ('hardmaterialapply_status', models.IntegerField(default=0)),
                ('visaapply_status', models.IntegerField(default=0)),
                ('houseticketapply_status', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('like', models.IntegerField()),
                ('read', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.CharField(max_length=5)),
                ('toefl_reading', models.CharField(max_length=5)),
                ('toefl_listening', models.CharField(max_length=5)),
                ('toefl_speaking', models.CharField(max_length=5)),
                ('toefl_writing', models.CharField(max_length=5)),
                ('toefl_total', models.CharField(max_length=5)),
                ('gre_verbal', models.CharField(max_length=5)),
                ('gre_quantitative', models.CharField(max_length=5)),
                ('gre_writing', models.CharField(max_length=5)),
                ('gre_total', models.CharField(max_length=5)),
                ('gmat', models.CharField(max_length=5)),
                ('ielts_reading', models.CharField(max_length=5)),
                ('ielts_listening', models.CharField(max_length=5)),
                ('ielts_speaking', models.CharField(max_length=5)),
                ('ielts_writing', models.CharField(max_length=5)),
                ('ielts_total', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseAndTicketApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='/Material/CV')),
                ('ps', models.FileField(upload_to='/Material/PS')),
                ('recommend_letter1', models.FileField(upload_to='/Material/RL')),
                ('recommend_letter2', models.FileField(upload_to='/Material/RL')),
                ('recommend_letter3', models.FileField(upload_to='/Material/RL')),
                ('recommend_letter1_status', models.IntegerField(default=0)),
                ('recommend_letter2_status', models.IntegerField(default=0)),
                ('recommend_letter3_status', models.IntegerField(default=0)),
                ('cv_status', models.IntegerField(default=0)),
                ('ps_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('school_link', models.URLField()),
                ('major_link', models.URLField()),
                ('application_link', models.URLField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VisaApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='trainee',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='gpa',
        ),
        migrations.AlterField(
            model_name='notification',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 3, 7, 46, 370000, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Trainee',
        ),
        migrations.AddField(
            model_name='article',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AbroadPassApp.Provider'),
        ),
        migrations.AddField(
            model_name='application',
            name='houseticketapply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='AbroadPassApp.HouseAndTicketApply'),
        ),
        migrations.AddField(
            model_name='application',
            name='materialapply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='AbroadPassApp.MaterialApply'),
        ),
        migrations.AddField(
            model_name='application',
            name='normaluser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='AbroadPassApp.NormalUser'),
        ),
        migrations.AddField(
            model_name='application',
            name='onlineapply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='AbroadPassApp.OnlineApply'),
        ),
        migrations.AddField(
            model_name='application',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='AbroadPassApp.Provider'),
        ),
        migrations.AddField(
            model_name='application',
            name='visaapply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='AbroadPassApp.VisaApply'),
        ),
    ]
