# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 08:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AbroadPassApp', '0010_auto_20160412_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='read',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 12, 8, 19, 11, 560000, tzinfo=utc)),
        ),
    ]
