# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 02:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AbroadPassApp', '0011_auto_20160412_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 15, 2, 4, 32, 186000, tzinfo=utc)),
        ),
    ]
