# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('birth', models.DateField(null=True)),
                ('province', models.CharField(max_length=50)),
                ('qq', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('locate_province', models.CharField(max_length=10)),
                ('locate_city', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=50)),
                ('gpa', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normaluser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('birth', models.DateField(null=True)),
                ('province', models.CharField(max_length=50)),
                ('qq', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('locate_province', models.CharField(max_length=10)),
                ('locate_city', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=50)),
                ('gpa', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
